### ISSUE TITLE
Replying to email does not pre-populate "To" field

### ISSUE THREAD

**Issue by aidan-fitz** [ascoderu/opwen-webapp#79] opened 2018-11-04 06:23 UTC
@holta says:

> Clicking `Reply` or `Reply all` does not pre-populate the email address(es) into the `To` field _(seems important!)_

at iiab/iiab#1282.

**Comment by c-w** [comment] 2018-11-04 20:51
Could you provide some more details on how to reproduce this? When I click on the "reply" or "reply all" icons in the inbox, the TO field gets set correctly for my local deployment:

Step 1: reply on email

![Screenshot showing inbox reply and reply all buttons](https://user-images.githubusercontent.com/1086421/47969688-ba89ea80-e07b-11e8-925b-a2a8368b749d.png)

Step 2: email TO field is set

![Screenshot showing email with populated TO field](https://user-images.githubusercontent.com/1086421/47969685-a7771a80-e07b-11e8-95d4-53a2b2457b42.png)

**Comment by c-w** [comment] 2018-11-12 15:15
Hi @holta. Thanks for the additional details. I've set up an IIAB instance on Ubuntu 18.04 (via `curl download.iiab.io/6.7/install.txt | sudo bash`) and played around with the Lokole install. Unfortunately I'm still unable to reproduce the issue.

Here is replying to an email:

![image](https://user-images.githubusercontent.com/1086421/48356011-56f75280-e663-11e8-99c3-004ce8540079.png)

Here is the populated to field:

![image](https://user-images.githubusercontent.com/1086421/48356051-66769b80-e663-11e8-9741-ef3c27c88eb5.png)

The same behavior also works for local emails:

![image](https://user-images.githubusercontent.com/1086421/48356265-e0a72000-e663-11e8-8a79-2dfa71cf8d26.png)

**Comment by holta** [comment] 2018-11-12 15:31
> Hi @holta. Thanks for the additional details. I've set up an IIAB instance on Ubuntu 18.04 (via `curl download.iiab.io/6.7/install.txt | sudo bash`) and played around with the Lokole install. Unfortunately I'm still unable to reproduce the issue.

Thanks @c-w

I feel terrible: I cannot reproduce on it on fresh/new installs of BIG-sized IIAB 6.7/master onto Raspbian Lite and Ubuntu 18.04

It would (seem) that running "./runrole lokole" might not be 100% equivalent to the above.

**Comment by c-w** [comment] 2018-11-12 16:05
Thanks for confirming @holta, and that does seem like an odd behavior. Is there anything you need from me at this point or are you happy with the state of this feature given that it works in the production setup?

**Comment by holta** [comment] 2018-11-12 16:34
> 
> 
> Thanks for confirming @holta, and that does seem like an odd behavior. Is there anything you need from me at this point or are you happy with the state of this feature given that it works in the production setup?

Agreed.  Let's declare victory for now.

And if this issue flares up again in future, when installers/implementers run `cd /opt/iiab/iiab` then `./runrole lokole` on an existing Internet-in-a-Box (IIAB), we can then ask them to:
1. instead install IIAB fresh / from scratch (http://download.iiab.io/6.7) on a new OS
2. offer us details if they can help us identify cause/effect

**Comment by c-w** [comment] 2018-11-12 18:54
Sounds good. Resolving. Thanks for all your help!

**Closed by c-w** 2018-11-12 18:54 UTC
